version: "3.9"

services:
  postgres-postgresql:
    hostname: postgres-postgresql
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    restart: always
    networks:
      - badgerdoc-taxonomy
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - .env

  taxonomy:
    build:
      context: .
      target: development
    ports:
      - ${APP_PORT}:${APP_PORT}
    env_file:
      - .env
    networks:
      - badgerdoc-taxonomy
    depends_on:
      postgres-postgresql:
        condition: service_healthy
    volumes:
      - ./:/opt/taxonomy/app
    restart: always

networks:
  badgerdoc-taxonomy:
    driver: bridge
