"""init

Revision ID: 5fd9d1fdcf5b
Revises:
Create Date: 2021-12-01 18:42:47.370459

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.


revision = "5fd9d1fdcf5b"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "heartbeat",
        sa.Column("id", postgresql.UUID(), nullable=False),
        sa.Column("last_heartbeat", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "main_event_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("date", sa.DateTime(), nullable=False),
        sa.Column("runner_id", postgresql.UUID(), nullable=True),
        sa.Column(
            "event",
            postgresql.JSONB(none_as_null=True, astext_type=sa.Text()),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "pipeline",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("version", sa.String(length=30), nullable=True),
        sa.Column("date", sa.DateTime(), nullable=False),
        sa.Column("meta", sa.JSON(none_as_null=True), nullable=True),
        sa.Column("steps", sa.JSON(none_as_null=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "pipeline_execution_task",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("date", sa.DateTime(), nullable=False),
        sa.Column("pipeline_id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=True),
        sa.Column("runner_id", postgresql.UUID(), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=True),
        sa.ForeignKeyConstraint(
            ["pipeline_id"], ["pipeline.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "execution_step",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("step_id", postgresql.UUID(), nullable=True),
        sa.Column("date", sa.DateTime(), nullable=False),
        sa.Column("init_args", sa.JSON(none_as_null=True), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=True),
        sa.Column("result", sa.JSON(none_as_null=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["task_id"], ["pipeline_execution_task.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("execution_step")
    op.drop_table("pipeline_execution_task")
    op.drop_table("pipeline")
    op.drop_table("main_event_log")
    op.drop_table("heartbeat")
    # ### end Alembic commands ###
