"""Add parent_step and tenant to execution_step

Revision ID: df42f45f4ddf
Revises: 29f072fb5c9c
Create Date: 2022-04-05 16:13:05.539298

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "df42f45f4ddf"
down_revision = "29f072fb5c9c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "execution_step",
        sa.Column("parent_step", postgresql.UUID(), nullable=True),
    )
    op.add_column(
        "execution_step",
        sa.Column("tenant", sa.String(length=50), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("execution_step", "tenant")
    op.drop_column("execution_step", "parent_step")
    # ### end Alembic commands ###
