# type: ignore
"""empty message

Revision ID: 13ac4bb3abd2
Revises: d1ddce2d5352
Create Date: 2021-11-10 14:42:23.459248

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "13ac4bb3abd2"
down_revision = "d1ddce2d5352"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "job",
        sa.Column(
            "all_files_data",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("job", "all_files_data")
    # ### end Alembic commands ###
