# type: ignore
"""empty message

Revision ID: 7511c6790067
Revises: 3f5b2d199d38
Create Date: 2021-11-29 12:16:13.307103

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "7511c6790067"
down_revision = "3f5b2d199d38"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "job", "users", nullable=True, new_column_name="annotators"
    )
    op.add_column(
        "job",
        sa.Column(
            "validators",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
    )
    op.add_column(
        "job",
        sa.Column(
            "owners", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "job", "annotators", nullable=True, new_column_name="users"
    )
    op.drop_column("job", "owners")
    op.drop_column("job", "validators")
    # ### end Alembic commands ###
