# type: ignore
"""empty message

Revision ID: 86f432539475
Revises: 83694c0b2df6
Create Date: 2021-12-27 18:19:21.227061

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "86f432539475"
down_revision = "83694c0b2df6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "job", sa.Column("import_source", sa.String(length=500), nullable=True)
    )
    op.add_column(
        "job", sa.Column("import_format", sa.String(length=50), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("job", "import_format")
    op.drop_column("job", "import_source")
    # ### end Alembic commands ###
