# type: ignore
"""empty message

Revision ID: 9229e70d2791
Revises:
Create Date: 2021-10-29 10:03:02.696875

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "9229e70d2791"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "job",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=250), nullable=True),
        sa.Column("status", sa.String(length=250), nullable=True),
        sa.Column(
            "files", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "datasets", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("creation_datetime", sa.DateTime(), nullable=True),
        sa.Column("type", sa.String(length=20), nullable=True),
        sa.Column(
            "users", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "categories",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column("is_auto_distribution", sa.Boolean(), nullable=True),
        sa.Column("deadline", sa.DateTime(), nullable=True),
        sa.Column("pipeline_id", sa.String(length=250), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("job")
    # ### end Alembic commands ###
