# type: ignore
"""empty message

Revision ID: d1ddce2d5352
Revises: 9229e70d2791
Create Date: 2021-11-09 14:52:44.125896

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "d1ddce2d5352"
down_revision = "9229e70d2791"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "job",
        "type",
        existing_type=sa.String(length=20),
        type_=sa.String(length=30),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "job",
        "type",
        existing_type=sa.String(length=30),
        type_=sa.String(length=20),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
