[tool.black]
line_length = 79

[tool.isort]
profile = "black"
line_length = 79

[tool.pylint.MAIN]
errors-only = "True"
max-line-length = 79

[tool.pylint.FORMAT]
errors-only = "True"
max-line-length = 79

[tool.pylint."MESSAGES CONTROL"]
disable = "E0401,E0611"

[tool.mypy]
ignore_missing_imports = true
scripts_are_modules = true
allow_untyped_decorators = true
strict = true
implicit_reexport = true
