"""Add proper constraint task_id fk in annotated_docs

Revision ID: 2074c50e0af1
Revises: 2b3ed53127ea
Create Date: 2021-12-15 13:36:54.214867

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "2074c50e0af1"
down_revision = "2b3ed53127ea"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        "annotated_docs_task_id_fkey",
        "annotated_docs",
        "tasks",
        ["task_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "annotated_docs_task_id_fkey", "annotated_docs", type_="foreignkey"
    )
    # ### end Alembic commands ###
