"""add agreement score table

Revision ID: 217182aef083
Revises: 65f11997f1d4
Create Date: 2022-12-12 16:49:18.079049

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "217182aef083"
down_revision = "65f11997f1d4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agreement_score",
        sa.Column(
            "annotator_id", postgresql.UUID(as_uuid=True), nullable=False
        ),
        sa.Column("job_id", sa.INTEGER(), nullable=False),
        sa.Column("task_id", sa.INTEGER(), nullable=False),
        sa.Column(
            "agreement_score",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["annotator_id"],
            ["users.user_id"],
        ),
        sa.ForeignKeyConstraint(
            ["job_id"], ["jobs.job_id"], ondelete="cascade"
        ),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"], ondelete="cascade"),
        sa.PrimaryKeyConstraint("annotator_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("agreement_score")
    # ### end Alembic commands ###
