"""added previous_jobs field

Revision ID: 591f639333f8
Revises: 62470ebd1429
Create Date: 2024-05-25 21:44:12.185480

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "591f639333f8"
down_revision = "62470ebd1429"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "files", sa.Column("previous_job_id", sa.INTEGER(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("files", "previous_job_id")
    # ### end Alembic commands ###
