"""stats

Revision ID: 65f11997f1d4
Revises: 66cd6054c2d0
Create Date: 2022-12-11 21:44:14.475708

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "65f11997f1d4"
down_revision = "66cd6054c2d0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "annotation_statistics",
        sa.Column("task_id", sa.INTEGER(), nullable=False),
        sa.Column(
            "event_type",
            postgresql.ENUM("opened", "closed", name="event_type"),
            nullable=False,
        ),
        sa.Column(
            "created",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated", sa.DateTime(), nullable=True),
        sa.Column(
            "additional_data",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"], ondelete="cascade"),
        sa.PrimaryKeyConstraint("task_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("annotation_statistics")
    # ### end Alembic commands ###
