"""add extensive_coverage parameter

Revision ID: 71095b8e6343
Revises: 66cd6054c2d0
Create Date: 2022-12-12 13:36:08.659682

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '71095b8e6343'
down_revision = '66cd6054c2d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jobs', 'validation_type',
               existing_type=postgresql.ENUM('cross', 'hierarchical', 'validation_only', name='validation_type'),
               type_=postgresql.ENUM('cross', 'hierarchical', 'validation_only', 'extensive_coverage', name='validationschema'),
               existing_nullable=False,
               existing_server_default=sa.text("'cross'::validation_type"))
    op.add_column('jobs', sa.Column('extensive_coverage', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jobs', 'validation_type',
               existing_type=postgresql.ENUM('cross', 'hierarchical', 'validation_only', 'extensive_coverage', name='validationschema'),
               type_=postgresql.ENUM('cross', 'hierarchical', 'validation_only', name='validation_type'),
               existing_nullable=False,
               existing_server_default=sa.text("'cross'::validation_type"))
    op.drop_column('jobs', 'extensive_coverage')
    # ### end Alembic commands ###
