"""compare agreement scores

Revision ID: 7cc1ed83c309
Revises: 9083dea3783e
Create Date: 2022-12-29 17:23:44.079258

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "7cc1ed83c309"
down_revision = "9083dea3783e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agreement_metrics",
        sa.Column("task_from", sa.INTEGER(), nullable=False),
        sa.Column("task_to", sa.INTEGER(), nullable=False),
        sa.Column("agreement_metric", sa.FLOAT(), nullable=False),
        sa.ForeignKeyConstraint(
            ["task_from"], ["tasks.id"], ondelete="cascade"
        ),
        sa.ForeignKeyConstraint(["task_to"], ["tasks.id"], ondelete="cascade"),
        sa.PrimaryKeyConstraint("task_from", "task_to"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("agreement_metrics")
    # ### end Alembic commands ###
