"""annotation statistics

Revision ID: b13e7ea70983
Revises: 66cd6054c2d0
Create Date: 2022-12-13 00:16:25.180295

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "b13e7ea70983"
down_revision = "66cd6054c2d0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agreement_score",
        sa.Column(
            "annotator_id", postgresql.UUID(as_uuid=True), nullable=False
        ),
        sa.Column("job_id", sa.INTEGER(), nullable=False),
        sa.Column("task_id", sa.INTEGER(), nullable=False),
        sa.Column(
            "agreement_score",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["annotator_id"],
            ["users.user_id"],
        ),
        sa.ForeignKeyConstraint(
            ["job_id"], ["jobs.job_id"], ondelete="cascade"
        ),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"], ondelete="cascade"),
        sa.PrimaryKeyConstraint("annotator_id"),
    )
    op.create_table(
        "annotation_statistics",
        sa.Column("task_id", sa.INTEGER(), nullable=False),
        sa.Column(
            "event_type",
            postgresql.ENUM("opened", "closed", name="event_type"),
            nullable=False,
        ),
        sa.Column(
            "created",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated", sa.DateTime(), nullable=True),
        sa.Column(
            "additional_data",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"], ondelete="cascade"),
        sa.PrimaryKeyConstraint("task_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("annotation_statistics")
    op.drop_table("agreement_score")
    # ### end Alembic commands ###
