"""Adds not-nullable tenant field to jobs table

Revision ID: d30649e367e0
Revises: 3a083a1fbba0
Create Date: 2021-11-19 12:06:52.545905

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d30649e367e0"
down_revision = "3a083a1fbba0"
branch_labels = None
depends_on = None


def upgrade():
    op.add_column("jobs", sa.Column("tenant", sa.VARCHAR(), nullable=True))
    op.execute("UPDATE jobs SET tenant = 'test'")
    op.alter_column("jobs", "tenant", nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("jobs", "tenant")
    # ### end Alembic commands ###
