apiVersion: v1
kind: Service
metadata:
    labels:
        app: badgerdoc-ui
    name: badgerdoc-ui
    namespace: { { .Release.Namespace } }
spec:
    ipFamilies:
        - IPv4
    ipFamilyPolicy: SingleStack
    ports:
        - port: 80
          protocol: TCP
          targetPort: 3000
    selector:
        app: badgerdoc-ui
    sessionAffinity: None
    type: ClusterIP
