apiVersion: v1
kind: Service
metadata:
  labels:
    app: "{{ template "svc.name" . }}"
  name: "{{ template "svc.name" . }}"
  namespace: {{ .Release.Namespace }}
spec:
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - port: {{ default .Values.global.servicePort .Values.servicePort }}
      protocol: TCP
      targetPort: 3000
  selector:
    app: "{{ template "svc.name" . }}"
  sessionAffinity: None
  type: "{{ default .Values.global.serviceType .Values.serviceType }}"