version: "3.9"

services:
  elasticsearch:
    image: amazon/opendistro-for-elasticsearch:latest
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - cluster.initial_master_nodes=es01
      - bootstrap.memory_lock=true
      - opendistro_security.disabled=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    healthcheck:
      test: curl --fail http://localhost:9200 || exit 1
      interval: 30s
      timeout: 3s
      retries: 10
      start_period: 30s
    networks:
      - badgerdoc-search
    ports:
      - "9202:9200"
    volumes:
      - elasticdata:/usr/share/elasticsearch/data
  #      - ./limits.conf:/etc/security/limits.conf

  backend:
    image: search
    container_name: search
    ports:
      - ${APP_PORT}:${APP_PORT}
    networks:
      - badgerdoc-search
    depends_on:
      elasticsearch:
        condition: service_healthy
    volumes:
      - .:/opt/search

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - badgerdoc-search

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      - badgerdoc-search

  embeddings:
    build: ./embeddings
    networks:
      - badgerdoc-search
    ports:
      - "0.0.0.0:3334:3334"
    volumes:
      - ./embeddings/main.py:/app/main.py


networks:
  badgerdoc-search:
    driver: bridge

volumes:
  elasticdata:
    driver: local
