import logging
import tempfile
from datetime import datetime, timedelta
from io import BytesIO
from typing import Any

from temporalio import activity, workflow
from temporalio.common import RetryPolicy

from badgerdoc_common.activities import document

logger = logging.getLogger(__name__)


@activity.defn
async def upload_example() -> document.BadgerdocDocument:
    logger.info("Starting upload example activity")

    current_timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"upload_example_{current_timestamp}"

    with tempfile.NamedTemporaryFile(mode="w+b", suffix=".txt") as temp_file:
        content = f"This is an example document created at {datetime.now().isoformat()}\n"
        content += "This file was generated by BadgerdocDocumentUploadExampleWorkflow.\n"
        temp_file.write(content.encode("utf-8"))
        temp_file.flush()

        doc = document.BadgerdocDocument(
            name=filename,
            extension="txt",
            metadata={"description": "Example document upload"},
            tags=[
                "upload_example",
            ],
        )

        temp_file.seek(0)
        file_content = temp_file.read()
        file_io = BytesIO(file_content)

        uploaded_document = await document.badgerdoc_upload_document(
            doc, file_io
        )

        logger.info(
            "Document uploaded successfully with ID: %s",
            uploaded_document.file,
        )

        return uploaded_document


@workflow.defn
class BadgerdocDocumentUploadExampleWorkflow:

    @workflow.run
    async def run(self) -> Any:
        logger.info("Starting BadgerDoc document upload example workflow")

        retry_policy = RetryPolicy(
            initial_interval=timedelta(seconds=1),
            backoff_coefficient=2.0,
            maximum_interval=timedelta(seconds=100),
            maximum_attempts=3,
        )

        try:
            uploaded_document = await workflow.execute_activity(
                upload_example,
                start_to_close_timeout=timedelta(seconds=60),
                retry_policy=retry_policy,
            )
        except Exception as e:
            logger.warning("Failed to upload document: %s", str(e))
            raise

        document_id = uploaded_document.id

        try:
            retrieved_document = await workflow.execute_activity(
                document.badgerdoc_get_document,
                document_id,
                start_to_close_timeout=timedelta(seconds=60),
                retry_policy=retry_policy,
            )
        except Exception as e:
            logger.warning("Failed to retrieve document: %s", str(e))
            raise

        logger.info("Document retrieved: %s", retrieved_document.name)

        return {
            "uploaded_document": uploaded_document,
            "retrieved_document": retrieved_document,
        }
