"""First Revision

Revision ID: 21e7e46d582c
Revises: 
Create Date: 2022-11-23 17:19:07.991151

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '21e7e46d582c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('taxonomy',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('tenant', sa.VARCHAR(), nullable=True),
    sa.Column('category_id', sa.VARCHAR(), nullable=False),
    sa.Column('latest', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('association_taxonomy_job',
    sa.Column('taxonomy_id', sa.VARCHAR(), nullable=False),
    sa.Column('job_id', sa.VARCHAR(), nullable=False),
    sa.ForeignKeyConstraint(['taxonomy_id'], ['taxonomy.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('taxonomy_id', 'job_id')
    )
    op.create_table('taxon',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('tenant', sa.VARCHAR(), nullable=True),
    sa.Column('taxonomy_id', sa.VARCHAR(), nullable=False),
    sa.Column('parent_id', sa.VARCHAR(), nullable=True),
    sa.Column('tree', sqlalchemy_utils.types.ltree.LtreeType(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['taxon.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['taxonomy_id'], ['taxonomy.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('index_taxon_tree', 'taxon', ['tree'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_taxon_parent_id'), 'taxon', ['parent_id'], unique=False)
    op.create_index(op.f('ix_taxon_taxonomy_id'), 'taxon', ['taxonomy_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_taxon_taxonomy_id'), table_name='taxon')
    op.drop_index(op.f('ix_taxon_parent_id'), table_name='taxon')
    op.drop_index('index_taxon_tree', table_name='taxon', postgresql_using='gist')
    op.drop_table('taxon')
    op.drop_table('association_taxonomy_job')
    op.drop_table('taxonomy')
    # ### end Alembic commands ###
