"""First Revision

Revision ID: bdea8a93cafe
Revises:
Create Date: 2022-11-24 16:36:12.022247

"""
import sqlalchemy as sa
import sqlalchemy_utils

from alembic import op

# revision identifiers, used by Alembic.
revision = "bdea8a93cafe"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "taxonomy",
        sa.Column("id", sa.VARCHAR(), nullable=False),
        sa.Column("name", sa.VARCHAR(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("tenant", sa.VARCHAR(), nullable=True),
        sa.Column("category_id", sa.VARCHAR(), nullable=False),
        sa.Column("latest", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id", "version"),
    )
    op.create_table(
        "association_taxonomy_job",
        sa.Column("taxonomy_id", sa.VARCHAR(), nullable=True),
        sa.Column("taxonomy_version", sa.Integer(), nullable=True),
        sa.Column("job_id", sa.VARCHAR(), nullable=False),
        sa.ForeignKeyConstraint(
            ["taxonomy_id", "taxonomy_version"],
            ["taxonomy.id", "taxonomy.version"],
        ),
        sa.PrimaryKeyConstraint("job_id"),
    )
    op.create_table(
        "taxon",
        sa.Column("id", sa.VARCHAR(), nullable=False),
        sa.Column("name", sa.VARCHAR(), nullable=False),
        sa.Column("tenant", sa.VARCHAR(), nullable=True),
        sa.Column("taxonomy_id", sa.VARCHAR(), nullable=True),
        sa.Column("taxonomy_version", sa.Integer(), nullable=True),
        sa.Column("parent_id", sa.VARCHAR(), nullable=True),
        sa.Column(
            "tree", sqlalchemy_utils.types.ltree.LtreeType(), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"], ["taxon.id"], ondelete="cascade"
        ),
        sa.ForeignKeyConstraint(
            ["taxonomy_id", "taxonomy_version"],
            ["taxonomy.id", "taxonomy.version"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "index_taxon_tree",
        "taxon",
        ["tree"],
        unique=False,
        postgresql_using="gist",
    )
    op.create_index(
        op.f("ix_taxon_parent_id"), "taxon", ["parent_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_taxon_parent_id"), table_name="taxon")
    op.drop_index(
        "index_taxon_tree", table_name="taxon", postgresql_using="gist"
    )
    op.drop_table("taxon")
    op.drop_table("association_taxonomy_job")
    op.drop_table("taxonomy")
    # ### end Alembic commands ###
