"""change category linking

Revision ID: d3ba69ca9d97
Revises: 48dc50decbed
Create Date: 2022-12-26 04:40:50.608253

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "d3ba69ca9d97"
down_revision = "48dc50decbed"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("association_taxonomy_job")
    op.execute("DELETE FROM association_taxonomy_category")
    op.drop_constraint(
        "association_taxonomy_category_pkey",
        "association_taxonomy_category",
        type_="primary",
    )
    op.add_column(
        "association_taxonomy_category",
        sa.Column("job_id", sa.VARCHAR(), nullable=False),
    )
    op.create_primary_key(
        "association_taxonomy_category_pkey",
        "association_taxonomy_category",
        ["taxonomy_id", "taxonomy_version", "category_id", "job_id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM association_taxonomy_category")
    op.drop_constraint(
        "association_taxonomy_category_pkey",
        "association_taxonomy_category",
        type_="primary",
    )
    op.create_primary_key(
        "association_taxonomy_category_pkey",
        "association_taxonomy_category",
        ["taxonomy_id", "taxonomy_version", "category_id"],
    )
    op.drop_column("association_taxonomy_category", "job_id")
    op.create_table(
        "association_taxonomy_job",
        sa.Column("taxonomy_id", sa.VARCHAR(), nullable=True),
        sa.Column("taxonomy_version", sa.Integer(), nullable=True),
        sa.Column("job_id", sa.VARCHAR(), nullable=False),
        sa.ForeignKeyConstraint(
            ["taxonomy_id", "taxonomy_version"],
            ["taxonomy.id", "taxonomy.version"],
        ),
        sa.PrimaryKeyConstraint("job_id"),
    )
    # ### end Alembic commands ###
