extraEnvs: []

image:
    registry: 818863528939.dkr.ecr.eu-central-1.amazonaws.com/badgerdoc
    tag: latest

imagePullPolicy: Always

podAnnotations:
    sidecar.istio.io/inject: "false"
labels:
    app: badgerdoc-ui

replicaCount: 1

resources: {}

schedulerName: default-scheduler

nameOverride: ""

affinity: {}
nodeSelector: {}
tolerations: []

securityContext: {}

servicePort: 80
serviceType: ClusterIP

updateStrategy:
    rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
    type: RollingUpdate