version: '3.9'

services:

  postgres-postgresql:
    image: postgres:13.4
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=scheduler
    ports:
      - "5432:5432"
    restart: always

  web:
    build:
      context: .
      target: tests
    container_name: scheduler_web_app
    env_file:
      - .env
    volumes:
      - .:/opt/scheduler/
    ports:
      - "8123:8123"
    command: tail -f /dev/null  # keeps the container running
    depends_on:
      - postgres-postgresql
    restart: on-failure

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    logging:
      driver: none
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
