fail_fast: true
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
        args: [--allow-multiple-documents]
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    - id: isort
      args:
        - --profile=black
        - --filter-files
        - --line-length=79
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    -   id: black
        args:
          - --line-length=79
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.1.1
    hooks:
      - id: mypy
        additional_dependencies: [types-requests, pydantic]
        name: mypy
        entry: mypy
        language: python
        types: [python]
        require_serial: true
        args:
          - --strict
          - --ignore-missing-imports
          - --allow-untyped-decorators
          - --python-version=3.8
-   repo: https://github.com/pycqa/pylint
    rev: v2.17.1
    hooks:
        - id: pylint
          types: [ python ]
          args:
            - --max-line-length=79
            - --errors-only
            - --disable=E0401
