# Base dockerfile for all workflows
ARG BASE_IMAGE=python:3.12-slim
FROM ${BASE_IMAGE}

COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /usr/local/bin/

WORKDIR /app

COPY badgerdoc_common ./badgerdoc_common

ENV PYTHONPATH=/app
ENV PYTHONUNBUFFERED=1
