"""add columns to basement

Revision ID: 5c3092bc3517
Revises: 8fd15e9edd28
Create Date: 2022-04-06 15:16:29.093715

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "5c3092bc3517"
down_revision = "8fd15e9edd28"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "basement", sa.Column("key_script", sa.String(), nullable=True)
    )
    op.add_column(
        "basement", sa.Column("key_archive", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("basement", "key_archive")
    op.drop_column("basement", "key_script")
    # ### end Alembic commands ###
