"""Create tables

Revision ID: 683f401ed33e
Revises:
Create Date: 2021-12-14 20:37:03.275893

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "683f401ed33e"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "basement",
        sa.Column("id", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String()),
        sa.Column(
            "supported_args",
            postgresql.JSON(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column("gpu_support", sa.Boolean()),
        sa.Column("created_by", sa.String()),
        sa.Column("created_at", sa.DateTime()),
        sa.Column("tenant", sa.String(length=100)),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "training",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String()),
        sa.Column("files_ids", sa.ARRAY(sa.Integer())),
        sa.Column("datasets_ids", sa.ARRAY(sa.Integer())),
        sa.Column("basement", sa.String(), nullable=False),
        sa.Column("epochs_count", sa.Integer()),
        sa.Column("kubeflow_pipeline_id", sa.String(), nullable=True),
        sa.Column("created_by", sa.String()),
        sa.Column("created_at", sa.DateTime()),
        sa.Column("tenant", sa.String(length=100)),
        sa.ForeignKeyConstraint(["basement"], ["basement.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "model",
        sa.Column("id", sa.String(length=15), nullable=False),
        sa.Column("name", sa.String()),
        sa.Column("basement", sa.String(), nullable=False),
        sa.Column(
            "data_path",
            postgresql.JSON(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            "configuration_path",
            postgresql.JSON(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column("training_id", sa.Integer(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("READY", "DEPLOYED", name="statusenum"),
            nullable=True,
        ),
        sa.Column("score", postgresql.DOUBLE_PRECISION(), nullable=True),
        sa.Column("categories", sa.ARRAY(sa.String())),
        sa.Column("created_by", sa.String()),
        sa.Column("created_at", sa.DateTime()),
        sa.Column("tenant", sa.String(length=100)),
        sa.ForeignKeyConstraint(["basement"], ["basement.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["training_id"],
            ["training.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("model")
    op.drop_table("training")
    op.drop_table("basement")
    op.execute("DROP TYPE statusenum;")
    # ### end Alembic commands ###
