"""modify basement and training

Revision ID: abeff4c79fd3
Revises: c769f68f00d4
Create Date: 2022-01-26 19:35:53.435357

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "abeff4c79fd3"
down_revision = "c769f68f00d4"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "training", sa.Column("jobs", sa.ARRAY(sa.Integer()), nullable=True)
    )
    op.drop_column("training", "datasets_ids")
    op.drop_column("training", "files_ids")
    op.drop_column("basement", "supported_args")
    op.add_column(
        "basement",
        sa.Column(
            "supported_args",
            sa.ARRAY(postgresql.JSON),
            server_default=None,
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "training",
        sa.Column(
            "files_ids",
            postgresql.ARRAY(sa.INTEGER()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "training",
        sa.Column(
            "datasets_ids",
            postgresql.ARRAY(sa.INTEGER()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("training", "jobs")
    op.drop_column("basement", "supported_args")
    op.add_column(
        "basement",
        sa.Column(
            "supported_args",
            postgresql.JSON(astext_type=sa.Text()),
            nullable=True,
            server_default=None,
        ),
    )
    # ### end Alembic commands ###
