"""Add field type to table model

Revision ID: c769f68f00d4
Revises: 683f401ed33e
Create Date: 2021-12-16 15:21:45.340186

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "c769f68f00d4"
down_revision = "683f401ed33e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("model", sa.Column("type", sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("model", "type")
    # ### end Alembic commands ###
