"""empty message

Revision ID: 0cadbdb7f0ea
Revises: 556834bc19db
Create Date: 2022-03-16 12:18:36.271859

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "0cadbdb7f0ea"
down_revision = "556834bc19db"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "heartbeat",
        sa.Column("id", postgresql.UUID(), nullable=False),
        sa.Column("last_heartbeat", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("units", sa.Column("runner_id", postgresql.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("units", "runner_id")
    op.drop_table("heartbeat")
    # ### end Alembic commands ###
