"""empty message

Revision ID: 3765da66361a
Revises:
Create Date: 2022-02-21 13:26:22.338453

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "3765da66361a"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "units",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("url", sa.String(), nullable=True),
        sa.Column("body", sa.JSON(none_as_null=True), nullable=True),
        sa.Column("result", sa.JSON(none_as_null=True), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("updated", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("units")
    # ### end Alembic commands ###
