"""empty message

Revision ID: 449be82736bd
Revises: 0cadbdb7f0ea
Create Date: 2022-03-17 11:44:15.994344

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "449be82736bd"
down_revision = "0cadbdb7f0ea"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("units", sa.Column("response_topic", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("units", "response_topic")
    # ### end Alembic commands ###
