"""empty message

Revision ID: 556834bc19db
Revises: 3765da66361a
Create Date: 2022-02-28 18:16:23.839211

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "556834bc19db"
down_revision = "3765da66361a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("units", sa.Column("tenant", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("units", "tenant")
    # ### end Alembic commands ###
