###################################################
# Creates image for test runner
#
#                        ##         .
#                  ## ## ##        ==
#               ## ## ## ## ##    ===
#           /"""""""""""""""""\___/ ===
#      ~~~ {~~ ~~~~ ~~~ ~~~~ ~~~ ~ /  ===- ~~~
#           \______ o           __/
#             \    \         __/
#              \____\_______/
#
# Author:  Nikolai Volkov <nikolai_volkov@epam.com>
# version: 0.1.0
#
###################################################
ARG TAG=20.10.10-alpine3.14
FROM docker:$TAG

RUN apk add --no-cache bash make git curl jq
