[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
asyncio_mode = auto

addopts =
    -v
    --tb=short
    --strict-markers
    --disable-warnings

env =
    BADGERDOC_REST_API_RETRY_POLICY = 1000,2,3,5

markers =
    asyncio: mark test as async
    unit: mark test as unit test
    integration: mark test as integration test
