apiVersion: v1
kind: Service
metadata:
  labels:
    app: convert
  name: convert
  namespace: "{{ .Release.Namespace }}"
spec:
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: convert
  sessionAffinity: None
  type: ClusterIP
