version: "3.8"

services:
  postgres:
    image: library/postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data
    restart: on-failure

  keycloak:
    image: jboss/keycloak
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    restart: on-failure

  minio:
    image: 'bitnami/minio:latest'
    ports:
      - '9000:9000'
    env_file:
      - .env

  app:
    build: .
    environment:
      KEYCLOAK_ENDPOINT: "http://keycloak:8080"
      S3_CREDENTIALS_PROVIDER: "minio"
      S3_ENDPOINT: "minio:9000"
    ports:
      - "8000:8000"
    depends_on:
      - keycloak
      - minio
    restart: on-failure
