apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: search
  name: search
  namespace: {{ .Release.Namespace }}
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: search
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      creationTimestamp: null
      labels:
        app: search
    spec:
      containers:
      - image: {{ .Values.image.registry }}/search:{{ .Values.image.tag }}
        imagePullPolicy: IfNotPresent
        name: search
        resources:
          requests:
            memory: "200Mi"
            cpu: "200m"
          limits:
            memory: "1200Mi"
            cpu: "600m"
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        env:
        - name: S3_ENDPOINT_URL
          value: "http://minio"
        - name: S3_LOGIN
          valueFrom:
            secretKeyRef:
              name: search
              key: S3_LOGIN
        - name: S3_PASS
          valueFrom:
            secretKeyRef:
              name: search
              key: S3_PASS
        - name: S3_BUCKET_NAME
          value: "search"
        - name: ES_HOST
          value: "elasticsearch"
        - name: ES_PORT
          value: "9200"
        command: ["/bin/sh"]
        args: ["-c", "uvicorn search.main:app --host 0.0.0.0 --port 8080 --root-path /api/v1/search"]
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
