/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as _rootIndexRouteImport } from './routes/__root.index'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as TasksIndexRouteImport } from './routes/tasks.index'
import { Route as DocumentsIndexRouteImport } from './routes/documents.index'
import { Route as TasksTaskIdRouteImport } from './routes/tasks.$taskId'
import { Route as DocumentsIdRouteImport } from './routes/documents.$id'

const _rootIndexRoute = _rootIndexRouteImport.update({
  id: '/__root/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksIndexRoute = TasksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TasksRoute,
} as any)
const DocumentsIndexRoute = DocumentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocumentsRoute,
} as any)
const TasksTaskIdRoute = TasksTaskIdRouteImport.update({
  id: '/$taskId',
  path: '/$taskId',
  getParentRoute: () => TasksRoute,
} as any)
const DocumentsIdRoute = DocumentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DocumentsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/documents': typeof DocumentsRouteWithChildren
  '/tasks': typeof TasksRouteWithChildren
  '/upload': typeof UploadRoute
  '/documents/$id': typeof DocumentsIdRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/': typeof _rootIndexRoute
  '/documents/': typeof DocumentsIndexRoute
  '/tasks/': typeof TasksIndexRoute
}
export interface FileRoutesByTo {
  '/upload': typeof UploadRoute
  '/documents/$id': typeof DocumentsIdRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/': typeof _rootIndexRoute
  '/documents': typeof DocumentsIndexRoute
  '/tasks': typeof TasksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/documents': typeof DocumentsRouteWithChildren
  '/tasks': typeof TasksRouteWithChildren
  '/upload': typeof UploadRoute
  '/documents/$id': typeof DocumentsIdRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/__root/': typeof _rootIndexRoute
  '/documents/': typeof DocumentsIndexRoute
  '/tasks/': typeof TasksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/documents'
    | '/tasks'
    | '/upload'
    | '/documents/$id'
    | '/tasks/$taskId'
    | '/'
    | '/documents/'
    | '/tasks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/upload'
    | '/documents/$id'
    | '/tasks/$taskId'
    | '/'
    | '/documents'
    | '/tasks'
  id:
    | '__root__'
    | '/documents'
    | '/tasks'
    | '/upload'
    | '/documents/$id'
    | '/tasks/$taskId'
    | '/__root/'
    | '/documents/'
    | '/tasks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DocumentsRoute: typeof DocumentsRouteWithChildren
  TasksRoute: typeof TasksRouteWithChildren
  UploadRoute: typeof UploadRoute
  _rootIndexRoute: typeof _rootIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/__root/': {
      id: '/__root/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof _rootIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/': {
      id: '/tasks/'
      path: '/'
      fullPath: '/tasks/'
      preLoaderRoute: typeof TasksIndexRouteImport
      parentRoute: typeof TasksRoute
    }
    '/documents/': {
      id: '/documents/'
      path: '/'
      fullPath: '/documents/'
      preLoaderRoute: typeof DocumentsIndexRouteImport
      parentRoute: typeof DocumentsRoute
    }
    '/tasks/$taskId': {
      id: '/tasks/$taskId'
      path: '/$taskId'
      fullPath: '/tasks/$taskId'
      preLoaderRoute: typeof TasksTaskIdRouteImport
      parentRoute: typeof TasksRoute
    }
    '/documents/$id': {
      id: '/documents/$id'
      path: '/$id'
      fullPath: '/documents/$id'
      preLoaderRoute: typeof DocumentsIdRouteImport
      parentRoute: typeof DocumentsRoute
    }
  }
}

interface DocumentsRouteChildren {
  DocumentsIdRoute: typeof DocumentsIdRoute
  DocumentsIndexRoute: typeof DocumentsIndexRoute
}

const DocumentsRouteChildren: DocumentsRouteChildren = {
  DocumentsIdRoute: DocumentsIdRoute,
  DocumentsIndexRoute: DocumentsIndexRoute,
}

const DocumentsRouteWithChildren = DocumentsRoute._addFileChildren(
  DocumentsRouteChildren,
)

interface TasksRouteChildren {
  TasksTaskIdRoute: typeof TasksTaskIdRoute
  TasksIndexRoute: typeof TasksIndexRoute
}

const TasksRouteChildren: TasksRouteChildren = {
  TasksTaskIdRoute: TasksTaskIdRoute,
  TasksIndexRoute: TasksIndexRoute,
}

const TasksRouteWithChildren = TasksRoute._addFileChildren(TasksRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  DocumentsRoute: DocumentsRouteWithChildren,
  TasksRoute: TasksRouteWithChildren,
  UploadRoute: UploadRoute,
  _rootIndexRoute: _rootIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
