# Generated by Django 5.2.7 on 2025-12-01 21:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import badgerdoc.models.document


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "file",
                    models.FileField(
                        upload_to=badgerdoc.models.document.document_upload_path
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        help_text="Metadata for the document",
                        null=True,
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "document",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="Extraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "temporal_job_id",
                    models.CharField(
                        blank=True,
                        help_text="Temporal workflow job ID for tracking",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("comment", models.TextField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extractions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extractions",
                        to="badgerdoc.document",
                    ),
                ),
            ],
            options={
                "db_table": "extraction",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("data_extraction", "Data Extraction"),
                            ("document_processing", "Document Processing"),
                            ("quality_review", "Quality Review"),
                            ("validation", "Validation"),
                            ("annotation", "Annotation"),
                        ],
                        help_text="Type of this task",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        help_text="Current status of the task",
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User assigned to this task",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_tasks",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="WorkflowRegistry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event_entity",
                    models.CharField(
                        blank=True,
                        choices=[("document", "Document"), ("task", "Task")],
                        help_text="Entity that triggers this workflow",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("on_create", "On Create"),
                            ("on_update", "On Update"),
                        ],
                        help_text="Type of event that triggers this workflow",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "document_types",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="JSON array of document types this workflow can process",
                    ),
                ),
                (
                    "temporal_workflow_type",
                    models.CharField(
                        help_text="Temporal workflow type/class name",
                        max_length=255,
                    ),
                ),
                (
                    "temporal_queue",
                    models.CharField(
                        help_text="Temporal task queue name", max_length=255
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this workflow is active and can be triggered",
                    ),
                ),
                (
                    "auto_trigger",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this workflow should be triggered automatically in case of event happening",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created this workflow registry entry",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workflow_registries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "workflow_registry",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EventTrigger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "temporal_workflow_id",
                    models.IntegerField(
                        help_text="Temporal workflow identifier"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        help_text="Current status of the event trigger",
                        max_length=20,
                    ),
                ),
                (
                    "payload",
                    models.JSONField(
                        blank=True, help_text="Event payload data", null=True
                    ),
                ),
                (
                    "message",
                    models.CharField(
                        blank=True,
                        help_text="Event message or description",
                        max_length=255,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        help_text="Document that triggered this event",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_triggers",
                        to="badgerdoc.document",
                    ),
                ),
                (
                    "event_registry",
                    models.ForeignKey(
                        help_text="Workflow registry entry associated with this event trigger",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_triggers",
                        to="badgerdoc.workflowregistry",
                    ),
                ),
            ],
            options={
                "db_table": "event_trigger",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "link_type",
                    models.CharField(
                        choices=[
                            ("related", "Related"),
                            ("parent", "Parent"),
                            ("child", "Child"),
                            ("version", "Version"),
                            ("duplicate", "Duplicate"),
                            ("reference", "Reference"),
                        ],
                        help_text="Type of relationship between documents",
                        max_length=50,
                    ),
                ),
                (
                    "dest",
                    models.ForeignKey(
                        help_text="Destination document in the relationship",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_links",
                        to="badgerdoc.document",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        help_text="Source document in the relationship",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_links",
                        to="badgerdoc.document",
                    ),
                ),
            ],
            options={
                "db_table": "document_link",
                "unique_together": {("source", "dest", "link_type")},
            },
        ),
        migrations.CreateModel(
            name="ExtractionPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("page_number", models.PositiveIntegerField()),
                (
                    "content",
                    models.JSONField(
                        default=dict,
                        help_text="Extracted content stored as JSON",
                    ),
                ),
                (
                    "extraction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pages",
                        to="badgerdoc.extraction",
                    ),
                ),
            ],
            options={
                "db_table": "extraction_page",
                "ordering": ["extraction", "page_number"],
                "unique_together": {("extraction", "page_number")},
            },
        ),
        migrations.CreateModel(
            name="TaskDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        help_text="Document associated with this task",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_assignments",
                        to="badgerdoc.document",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        help_text="Task associated with this document",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_documents",
                        to="badgerdoc.task",
                    ),
                ),
            ],
            options={
                "db_table": "user_task_document",
                "unique_together": {("task", "document")},
            },
        ),
        migrations.CreateModel(
            name="TaskExtraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "extraction",
                    models.ForeignKey(
                        help_text="Extraction associated with this task",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_assignments",
                        to="badgerdoc.extraction",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        help_text="Task associated with this extraction",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_extractions",
                        to="badgerdoc.task",
                    ),
                ),
            ],
            options={
                "db_table": "user_task_extraction",
                "unique_together": {("task", "extraction")},
            },
        ),
        migrations.AddIndex(
            model_name="workflowregistry",
            index=models.Index(
                fields=["event_type"], name="idx_workflow_event_type"
            ),
        ),
        migrations.AddIndex(
            model_name="workflowregistry",
            index=models.Index(
                fields=["is_active"], name="idx_workflow_is_active"
            ),
        ),
        migrations.AddIndex(
            model_name="workflowregistry",
            index=models.Index(
                fields=["event_type", "is_active"],
                name="idx_workflow_event_active",
            ),
        ),
    ]
