# Generated by Django 5.2.7 on 2025-12-03 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("badgerdoc", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="extraction",
            name="status",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
