# Generated by Django 5.2.7 on 2025-12-05 09:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("badgerdoc", "0002_alter_extraction_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "verbose_name_plural": "Task statuses",
                "db_table": "task_status",
                "ordering": ["id"],
            },
        ),
        migrations.AlterUniqueTogether(
            name="taskdocument",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="taskextraction",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="task",
            name="task_type",
            field=models.CharField(
                choices=[
                    ("document", "Document"),
                    ("extraction", "Extraction"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="taskdocument",
            name="document",
            field=models.ForeignKey(
                help_text="Link document to task in case if task type: Document",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="document_tasks",
                to="badgerdoc.document",
            ),
        ),
        migrations.AlterField(
            model_name="taskdocument",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="task_documents",
                to="badgerdoc.task",
            ),
        ),
        migrations.AlterField(
            model_name="taskextraction",
            name="extraction",
            field=models.ForeignKey(
                help_text="Link extraction to task in case if task type: Extraction",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="task_assignments",
                to="badgerdoc.extraction",
            ),
        ),
        migrations.AlterField(
            model_name="taskextraction",
            name="task",
            field=models.ForeignKey(
                help_text="Link task to extraction in case if task type: Extraction",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="task_extractions",
                to="badgerdoc.task",
            ),
        ),
        migrations.AddConstraint(
            model_name="taskdocument",
            constraint=models.UniqueConstraint(
                fields=("task",), name="unique_task_document"
            ),
        ),
        migrations.AddConstraint(
            model_name="taskextraction",
            constraint=models.UniqueConstraint(
                fields=("task",), name="unique_task_extraction"
            ),
        ),
        migrations.AlterModelTable(
            name="taskdocument",
            table="task_document",
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tasks",
                to="badgerdoc.taskstatus",
            ),
        ),
    ]
