# Generated by Django 5.2.7 on 2025-12-05 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "badgerdoc",
            "0003_taskstatus_alter_taskdocument_unique_together_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eventtrigger",
            name="document",
        ),
        migrations.RemoveField(
            model_name="eventtrigger",
            name="event_registry",
        ),
        migrations.DeleteModel(
            name="DocumentLink",
        ),
        migrations.DeleteModel(
            name="EventTrigger",
        ),
    ]
