# Generated by Django 5.2.7 on 2025-12-08 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("badgerdoc", "0004_remove_eventtrigger_document_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="extraction",
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    (
                        "view_other_users_extractions",
                        "Can view other users extractions",
                    )
                ],
            },
        ),
    ]
