# Generated by Django 5.2.7 on 2025-12-09 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("badgerdoc", "0005_alter_extraction_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="document",
            options={
                "ordering": ["-updated_at"],
                "permissions": [
                    (
                        "view_other_users_document",
                        "Can view other users document",
                    )
                ],
            },
        ),
    ]
