# Generated by Django 5.2.7 on 2025-12-09 17:32

from django.db import migrations, models

from badgerdoc.models import _validation


class Migration(migrations.Migration):
    dependencies = [
        (
            "badgerdoc",
            "0007_alter_task_options_task_created_at_task_updated_at",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="extraction",
            name="tags",
            field=models.JSONField(
                blank=True,
                help_text="List of tags as strings",
                null=True,
                validators=[_validation.validate_tag_list],
            ),
        ),
    ]
