# Generated by Django 5.2.7 on 2025-12-09 17:53

from django.db import migrations, models

import badgerdoc.models._validation


class Migration(migrations.Migration):

    dependencies = [
        ("badgerdoc", "0008_extraction_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="tags",
            field=models.JSONField(
                blank=True,
                help_text="List of tags as strings",
                null=True,
                validators=[badgerdoc.models._validation.validate_tag_list],
            ),
        ),
    ]
