# Generated by Django 5.2.7 on 2025-12-17 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("badgerdoc", "0009_document_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="parent_document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="child_documents",
                to="badgerdoc.document",
            ),
        ),
    ]
