# Generated by Django 5.2.7 on 2026-01-08 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("badgerdoc", "0010_document_parent_document"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="extension",
            field=models.CharField(
                blank=True, help_text="File extension", max_length=8, null=True
            ),
        ),
    ]
