# Generated by Django 5.2.7 on 2026-01-15 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("badgerdoc", "0011_document_extension"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="taskstatus",
            options={
                "ordering": ["order"],
                "verbose_name_plural": "Task statuses",
            },
        ),
        migrations.AddField(
            model_name="taskstatus",
            name="order",
            field=models.PositiveIntegerField(default=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="taskstatus",
            name="parent",
            field=models.ManyToManyField(
                blank=True, related_name="children", to="badgerdoc.taskstatus"
            ),
        ),
    ]
