# Generated by Django 5.2.7 on 2026-01-15 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("badgerdoc", "0011_document_extension"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="document",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="badgerdoc.document",
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="TaskDocument",
        ),
    ]
