# Generated by Django 5.2.7 on 2026-01-16 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "badgerdoc",
            "0012_alter_taskstatus_options_taskstatus_order_and_more",
        ),
        ("badgerdoc", "0012_task_document_delete_taskdocument"),
    ]

    operations = []
