# Generated by Django 5.2.7 on 2026-01-16 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("badgerdoc", "0013_merge_20260116_1143"),
    ]

    operations = [
        migrations.AlterField(
            model_name="extraction",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Started", "Started"),
                    ("In progress", "In progress"),
                    ("Completed", "Completed"),
                    ("Timed out", "Timed out"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
