# Generated by Django 5.2.7 on 2026-01-21 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("badgerdoc", "0014_alter_extraction_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="task_type",
        ),
    ]
