# Generated by Django 5.2.7 on 2026-01-21 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("badgerdoc", "0015_remove_task_task_type"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="taskextraction",
            name="unique_task_extraction",
        ),
        migrations.AddConstraint(
            model_name="taskextraction",
            constraint=models.UniqueConstraint(
                fields=("task", "extraction"), name="unique_task_extraction"
            ),
        ),
    ]
