# Generated by Django 5.2.7 on 2026-01-27 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "badgerdoc",
            "0016_remove_taskextraction_unique_task_extraction_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ExtractionDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "content",
                    models.JSONField(
                        default=dict,
                        help_text="Extracted content stored as JSON",
                    ),
                ),
                (
                    "extraction",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extraction_document",
                        to="badgerdoc.extraction",
                    ),
                ),
            ],
            options={
                "db_table": "extraction_document",
                "ordering": ["extraction"],
            },
        ),
    ]
