# Generated by Django 5.2.7 on 2026-02-03 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("badgerdoc", "0018_alter_workflowregistry_event_entity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workflowregistry",
            name="event_entity",
            field=models.CharField(
                blank=True,
                choices=[
                    ("document", "Document"),
                    ("task", "Task"),
                    ("extraction", "Extraction"),
                    ("search_parameters", "Search Parameters"),
                ],
                help_text="Entity that triggers this workflow",
                max_length=50,
                null=True,
            ),
        ),
    ]
