# Generated by Django 5.2.7 on 2026-02-05 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("badgerdoc", "0019_alter_workflowregistry_event_entity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskstatus",
            name="name",
            field=models.CharField(max_length=50),
        ),
    ]
