# Generated by Django 5.2.7 on 2026-02-04 08:46

from django.db import migrations, models

import badgerdoc.models.document


class Migration(migrations.Migration):

    dependencies = [
        ("badgerdoc", "0020_alter_taskstatus_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="file",
            field=models.FileField(
                null=True,
                upload_to=badgerdoc.models.document.document_upload_path,
            ),
        ),
    ]
