# Generated by Django 5.2.7 on 2026-02-17 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("badgerdoc", "0021_alter_document_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workflowregistry",
            name="auto_trigger",
        ),
        migrations.AddField(
            model_name="workflowregistry",
            name="trigger",
            field=models.CharField(
                choices=[("manual", "Manual"), ("automatic", "Automatic")],
                default="automatic",
                help_text="How this workflow should be triggered",
                max_length=20,
            ),
        ),
    ]
