# Generated by Django 5.2.7 on 2026-02-17 10:22

from django.db import migrations, models

import badgerdoc.models._validation


class Migration(migrations.Migration):

    dependencies = [
        ("badgerdoc", "0022_remove_workflowregistry_auto_trigger_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflowregistry",
            name="extraction_scope",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="JSON array of extraction scopes this workflow can process (document, page, extraction)",
                validators=[
                    badgerdoc.models._validation.validate_extraction_scope_list
                ],
            ),
        ),
    ]
