# Generated by Django 5.2.7 on 2026-02-25 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("badgerdoc", "0023_workflowregistry_extraction_scope"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag", models.CharField(max_length=50, unique=True)),
                (
                    "literal",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("order", models.PositiveIntegerField()),
            ],
            options={
                "verbose_name_plural": "Tags",
                "db_table": "tag",
                "ordering": ["order"],
            },
        ),
    ]
