# Generated by Django 5.2.7 on 2026-03-16 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("badgerdoc", "0024_tag"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="document",
            options={
                "ordering": ["-updated_at"],
                "permissions": [
                    (
                        "view_other_users_document",
                        "Can view other users document",
                    ),
                    ("can_delete_document", "Can delete document"),
                ],
            },
        ),
    ]
