# Generated by Django 5.2.7 on 2026-03-17 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("badgerdoc", "0025_alter_document_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="Document name",
                max_length=1024,
                null=True,
            ),
        ),
    ]
