# Generated by Django 5.2.7 on 2026-03-13 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("badgerdoc", "0026_document_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="extractionpage",
            name="content",
            field=models.TextField(
                default="", help_text="Extracted content stored as text"
            ),
        ),
    ]
