# Generated by Django 5.2.7 on 2026-04-01 12:18

from django.db import migrations, models

import badgerdoc.models._validation


class Migration(migrations.Migration):

    dependencies = [
        ("badgerdoc", "0027_alter_extractionpage_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflowregistry",
            name="support_prompts",
            field=models.BooleanField(
                default=False,
                help_text="Whether this workflow supports additional user prompts",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="tags",
            field=models.JSONField(
                blank=True,
                help_text="List of tags as strings",
                null=True,
                validators=[badgerdoc.models._validation.validate_tag_list],
            ),
        ),
        migrations.AddField(
            model_name="workflowregistry",
            name="entity_tags",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="JSON array of entity tags this workflow can process. Matches tags from the event_entity (document, task, or extraction)",
            ),
        ),
    ]
