# Generated by Django 5.2.7 on 2026-04-06 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("badgerdoc", "0028_workflowregistry_document_tags_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflowregistry",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="Human-readable name for this workflow",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="workflowregistry",
            name="tags",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="JSON array of tags related to this workflow",
            ),
        ),
    ]
