# Generated by Django 5.2.7 on 2026-05-11 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("badgerdoc", "0029_workflowregistry_name_workflowregistry_tags"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("DEBUG", "Debug"),
                            ("INFO", "Info"),
                            ("WARNING", "Warning"),
                            ("ERROR", "Error"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="INFO",
                        max_length=8,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("Temporal", "Temporal"),
                            ("Django", "Django"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "log",
                    models.JSONField(
                        help_text="Structured log payload (stored as JSONB)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_logs",
                        to="badgerdoc.document",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agent_logs",
                        to="badgerdoc.task",
                    ),
                ),
            ],
            options={
                "db_table": "badgerdoc_agent_log",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["document", "created_at"],
                        name="badgerdoc_a_documen_b99e2d_idx",
                    ),
                    models.Index(
                        fields=["document", "task", "created_at"],
                        name="badgerdoc_a_documen_166da4_idx",
                    ),
                ],
            },
        ),
    ]
