# Generated by Django 5.2.7 on 2026-05-14 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("badgerdoc", "0030_agentlog"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="agentlog",
            options={
                "ordering": ["created_at"],
                "permissions": [("can_write_log", "Can write agent log")],
            },
        ),
    ]
