# Generated by Django 5.2.7 on 2026-05-14 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("badgerdoc", "0031_alter_agentlog_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentlog",
            name="path",
            field=models.CharField(db_index=True, default="", max_length=1024),
        ),
        migrations.AlterField(
            model_name="agentlog",
            name="log",
            field=models.JSONField(),
        ),
    ]
