version: "3.9"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.2
    container_name: elastic
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    restart: always
    healthcheck:
      test: curl --fail http://localhost:9200 || exit 1
      interval: 30s
      timeout: 3s
      retries: 10
      start_period: 30s
    ports:
      - ${ES_PORT}:${ES_PORT}
    networks:
      - bd-annotation-search

  search:
    image: search
    container_name: search
    ports:
      - ${SEARCH_PORT}:${APP_PORT}
    networks:
      - bd-annotation-search
    depends_on:
      elasticsearch:
        condition: service_healthy

  postgres-postgresql:
    image: postgres:13.4
    container_name: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    restart: always
    networks:
      - bd-annotation-search
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      - search

  annotation:
    image: annotation
    container_name: annotation
    ports:
      - ${ANNOTATION_PORT}:${APP_PORT}
    networks:
      - bd-annotation-search
    depends_on:
      postgres-postgresql:
        condition: service_healthy

networks:
  bd-annotation-search:
    driver: bridge
