name: badgerdoc_cli linters and tests
on:
  push:
    paths:
      - lib/badgerdoc_cli/**
      - .github/worlflows/badgerdoc-cli.yml
  pull_request:
    paths:
      - lib/badgerdoc_cli/**
      - .github/worlflows/badgerdoc-cli.yml
jobs:
  badgerdoc-cli-test:
    strategy:
      matrix:
        python-version: [ "3.8.15" ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Install dependencies
        working-directory: ./lib/badgerdoc_cli
        run: |
          python -m pip install --upgrade pip
          pip install ".[dev]"
      - name: Run linters and checkers [isort -> black -> mypy -> pylint]
        working-directory: ./lib/badgerdoc_cli
        run: |
          git ls-files -- . | xargs pre-commit run --files
      - name: Run tests
        working-directory: ./lib/badgerdoc_cli
        run: |
          pytest tests/
