name: badgerdoc

on:
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - "**"
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

env:
  PYTHON_VERSION: 3.8

jobs:
  linters:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --only dev
      - name: Run Isort
        run: |
          poetry run isort --diff --check-only .
      - name: Run Black
        run: |
          poetry run black --config pyproject.toml --diff --check .
  build:
    if: github.event_name == 'pull_request' && github.base_ref == 'main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build services
        run: make build_badgerdoc
  semantic_pr:
    if: github.event_name == 'pull_request_target'
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
