name: convert precommit and test
run-name: convert precommit and test
on:
  pull_request:
    paths:
      - convert/**
      - .github/workflows/convert.yml
jobs:
  convert:
    strategy:
      matrix:
        python-version: ["3.12.1"]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        working-directory: ./convert
        run: |
          python -m pip install --upgrade pip
          pip install lockfile==0.12.2
          pip install poetry==1.7.1
          pip install 'setuptools<72.0.0' # some legacy dependencies requires this
          pip install pre-commit
          poetry install --all-extras
          poetry add ../lib/filter_lib
          poetry add ../lib/tenants
          poetry add ../lib/badgerdoc_storage
      - name: Run linters and checkers [mypy -> pylint]
        working-directory: ./convert
        run: |
          git ls-files -- . | xargs pre-commit run mypy --files
          git ls-files -- . | xargs pre-commit run pylint --files
      # Disabling tests, needs to be recreated
      # https://github.com/epam/badgerdoc/issues/885
      #- name: Run tests
      #  working-directory: ./convert
      #  run: |
      #     poetry run pytest tests
