name: convert precommit and test
run-name: convert precommit and test
on:
  pull_request:
    paths:
      - convert/**
      - .github/workflows/convert.yml
jobs:
  convert:
    strategy:
      matrix:
        python-version: [ "3.8.10" ]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        working-directory: ./convert
        run: |
           python -m pip install --upgrade pip
           pip install lockfile==0.12.2
           pip install poetry==1.3.0
           pip install pre-commit
           poetry install --all-extras
           poetry add --editable ../lib/filter_lib
           poetry add --editable ../lib/tenants
      - name: Run linters and checkers [mypy -> pylint]
        working-directory: ./convert
        run: |
          git ls-files -- . | xargs pre-commit run mypy --files
          git ls-files -- . | xargs pre-commit run pylint --files
      - name: Run tests
        working-directory: ./convert
        run: |
           poetry run pytest tests
