name: convert precommit and test
run-name: convert precommit and test
on:
  push: []
#    paths:
#      - convert/**
#      - .github/worlflows/convert.yml
jobs:
  convert-pre-commit-actions:
    strategy:
      matrix:
        python-version: [ "3.8.15" ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Run isort
        uses: isort/isort-action@v1.1.0
        with:
          sort-paths: convert/*
          configuration:
            --check-only
            --profile=black
            --line-length=79
            --skip=tests
      - name: Black
        uses: psf/black@stable
        with:
          options: "--line-length=79"
      - run: pip install flake8
      - run: flake8 --extend-ignore=E203 annotation
  annotation-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.8.15" ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          cd convert
          pip install poetry
          poetry run pytest