name: ml-server
run-name: ml-server
on:
  push:
    paths:
      - "ml_server/**"
      - ".github/workflows/ml-server.yml"
  pull_request:
    paths:
      - "ml_server/**"
      - ".github/workflows/ml-server.yml"
jobs:
  linters:
    strategy:
      matrix:
        python-version: ["3.12.1"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
      - run: pip install flake8
      - run: flake8 --extend-ignore=E203 ml_server
