name: tenants precommit and test
run-name: tenants precommit and test
on:
  push:
    paths:
      - lib/python3.12/tenants/**
      - .github/worlflows/python3.12/tenants.yml
  pull_request:
    paths:
      - lib/python3.12/tenants/**
      - .github/worlflows/python3.12/tenants.yml
jobs:
  tenants-pre-commit-actions:
    strategy:
      matrix:
        python-version: [ "3.12.0", "3.12.1" ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Run isort
        uses: isort/isort-action@v1.1.0
        with:
          sort-paths: lib/python3.12/tenants/*
          configuration:
            --check-only
            --profile=black
            --line-length=79
            --skip=tests
      - name: Black
        uses: psf/black@stable
        with:
          src: "lib/python3.12/tenants"
          options: '--check --line-length=79 --exclude="tests" --verbose'
      - run: pip install flake8
      - run: flake8 --exclude=tests --extend-ignore=E203 lib/python3.12/tenants
  tenants-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.12.0", "3.12.1" ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          cd lib/python3.12/tenants
          pip install ".[dev]"
      - name: Test with pytest
        run: |
          cd lib/python3.12/tenants
          pytest
