name: taxonomy

on:
  push:
    paths:
      - taxonomy/**
      - .github/worlflows/taxonomy.yml
  pull_request:
    paths:
      - taxonomy/**
      - .github/worlflows/taxonomy.yml
jobs:
  linters-and-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12.1"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        working-directory: ./taxonomy
        run: |
          python -m pip install --upgrade pip
          pip install poetry>=1.7.1
          poetry install --no-root
          poetry add ../lib/python3.12/filter_lib
          poetry add ../lib/python3.12/tenants
      - name: Run linters and checkers [flake8]
        working-directory: ./taxonomy
        run: |
          poetry run flake8 --extend-ignore=E203 taxonomy/
      - name: Run tests
        working-directory: ./taxonomy
        run: |
          poetry run pytest tests/
