name: taxonomy linters and tests

on:
  push:
    paths:
      - taxonomy/**
      - .github/worlflows/taxonomy.yml
  pull_request:
    paths:
      - taxonomy/**
      - .github/worlflows/taxonomy.yml
jobs:
   taxonomy-linters-and-tests:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
       - name: update docker-compose
         run: pip install --upgrade docker-compose
       - name: create base image
         run: cd infra/docker/python_base && make build image_name=818863528939.dkr.ecr.eu-central-1.amazonaws.com/badgerdoc/python_base:0.1.7
       - name: run docker-compose up
         run: cd taxonomy && docker-compose up -d --build
       - name: run tests
         run: docker exec taxonomy_web_app bash -c "poetry run pytest"
       - name: check with flake8
         run: docker exec taxonomy_web_app bash -c "flake8 --exclude=alembic,tests,poetry --extend-ignore=E203"
       - name: check with isort
         run: docker exec taxonomy_web_app bash -c "isort --profile=black --line-length=79 --check-only --skip=alembic --skip=tests --skip=poetry ."
       - name: check with black
         run: docker exec taxonomy_web_app bash -c 'black --check --line-length=79 --exclude="(alembic|tests|poetry)" .'
