apiVersion: apps/v1
kind: Deployment
metadata:
  name: models-deployment
  namespace: dev2
  labels:
    app: models
spec:
  replicas: 1
  selector:
    matchLabels:
      app: models
  template:
    metadata:
      labels:
        app: models
    spec:
      containers:
      - name: models
        image: localhost:5000/models:v1.0
        securityContext:
          privileged: true  # temporary solution for closed infrastructure
        ports:
        - containerPort: 8080
        env:
        - name: POSTGRES_HOST
          value: db
        - name: POSTGRES_USER
          value: admin
        - name: POSTGRES_PASSWORD
          value: admin
        - name: POSTGRES_DB
          value: models
        - name: S3_ACCESS_KEY
          value: minio
        - name: S3_SECRET_KEY
          value: minio123
        - name: S3_ENDPOINT
          value: minio:9000
        - name: KEYCLOAK_SYSTEM_USER_SECRET
          value: some_secret_key
        - name: INFERENCE_HOST
          value: "127.0.0.1"
        - name: INFERENCE_PORT
          value: "8000"
        - name: DOCKER_REGISTRY_URL
          value: "localhost:5000"
        - name: MODELS_NAMESPACE
          value: dev2
        - name: ROOT_PATH
          value: ""
        - name: DOMAIN_NAME
          value: badgerdoc.com
      serviceAccountName: model-deployer
