image: docker:stable

variables:
  ARTIFACTORY_URL: $ARTIFACTORY_URL
  ARTIFACTORY_USER: $ARTIFACTORY_USER
  ARTIFACTORY_PASS: $ARTIFACTORY_PASS
  AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
  AWS_URL: 818863528939.dkr.ecr.eu-central-1.amazonaws.com
  DOCKERFILE: ./deploy/web.Dockerfile

workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH == "master"'
    - if: '$CI_PIPELINE_SOURCE == "web"'

before_script:
  - export CI="true"
  - export PATH=$PATH:/usr/local/bin
  - apk update && apk add ca-certificates && apk add bash
  - version="$(cat version.txt)-${CI_COMMIT_SHORT_SHA}"

stages:
  - test
  - build
  - deploy
  - clean

build_dev:
  stage: build
#  tags:
#    - badgerdoc
  services:
    - docker:dind
  except:
    - schedules
  script:
    - bash ./deploy/install_aws.sh
    - docker login -u ${ARTIFACTORY_USER} -p ${ARTIFACTORY_PASS} ${ARTIFACTORY_URL}
    - docker build -t artifactory.epam.com:6144/badgerdoc/badgerdoc_ui_dev:${version} --no-cache=true --pull --file $DOCKERFILE .
    - docker push artifactory.epam.com:6144/badgerdoc/badgerdoc_ui_dev:${version}
    - docker tag artifactory.epam.com:6144/badgerdoc/badgerdoc_ui_dev:${version} ${AWS_URL}/badgerdoc/badgerdoc_ui:${version}
    - aws ecr get-login-password --region ${AWS_DEFAULT_REGION} | docker login --username AWS --password-stdin ${AWS_URL}
    - docker push ${AWS_URL}/badgerdoc/badgerdoc_ui:${version}
    
deploy_dev:
  stage: deploy
  variables:
    DEPLOY_ENV: "dev1"
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: never

    - if: '$CI_PIPELINE_SOURCE == "web"'
      when: on_success
      variables:
        DEPLOY_ENV: "dev2"

    - when: on_success
  tags:
    - kluster-runner
  image: 
    name: 818863528939.dkr.ecr.eu-central-1.amazonaws.com/badgerdoc/helm_gitlab_runner:0.1.4
    entrypoint: [""]
  script:
    - helm upgrade -n ${DEPLOY_ENV} -i --set image.tag=${version} badgerdoc-ui-dev chart/.

clean_dev:
  stage: clean
  services:
  - docker:dind
  rules:
    - when: always
#  tags:
#    - badgerdoc
  script:
     - echo "claning is on schedule"
#    - docker container prune -f
#    - docker image prune -fa
